server:
  port: 8081

spring:
  application:
    name: provide-server
  cloud:
    nacos:
      serverAddr: 47.97.117.93:8848
      discovery:
        namespace: 028a1914-3c25-4b7b-9453-d39c9f15d516

